# This is a TOML document

title = "Training configuration"

[mode]
gpu = true

[paths]
tmp_data_path = "./tmp_files"

[general]
num_epochs = 100
num_classes = 10
valid_split = 0.2
loss_func = "cross_entropy"
optimizer= "adam"
arch = "Model_1"

[source]
source = "torchvision"
set = "MNIST"

[hyperparams]
batch_size = 64
lr = 1e-05

#call callbacks alwasys like this: callbacks.*
[callbacks.monitor]
monitor = ["valid_acc", "valid_loss", "train_loss"]
verbose = true


[callbacks.earlystopping]
monitor = "valid_loss"
patience = 1
