# This is a TOML document

title = "Training configuration"

[mode]
gpu = false

[paths]
tmp_data_path = "./tmp_files"

[general]
num_epochs = 100
num_classes = 10
valid_split = 0.2
loss_func = "cross_entropy"
optimizer= "adam"
[source]
source = "torchvision"
set = "MNIST"

[hyperparams]
batch_size = 64
lr = 1e-05

#call callbacks alwasys like this: callbacks.*
[callbacks.monitor]
monitor = ["valid_acc", "valid_loss", "loss"]
print2console = true

[callbacks.earlystopping]
monitor = "valid_loss"
patience = 1000
