# This is a TOML document

title = "Training configuration"

[mode]
gpu = true

[paths]
tmp_data_path = "./tmp_files"

[general]
num_epochs = 100
num_classes = 10
valid_split = 0.2
loss_func = "cross_entropy"
optimizer= "Adam"
arch = "Model_CNN"

[source]
source = "torchvision"
set = "MNIST"

[hyperparams]
batch_size = 64
lr = 1e-05

#call callbacks alwasys like this: callbacks.*
[callbacks.monitor]
monitor = ["valid_acc", "valid_loss", "train_loss"]
verbose = true

[callbacks.earlystopping]
monitor = "valid_loss"
patience = 10
delta = 1e-10

[callbacks.checkpoints]
monitor = "valid_loss"
ckp_path = "/content/gdrive/MyDrive/Marcel_Moczarski/Data_Science/Google_Services/Local_Drive_Storage/Conda_Envs/Template_Project/checkpoints"
no_time_path = "ckp_dir"
save_best_model = true
save_best_history = true
use_last_run = false
